# Generated by Django 6.0.5 on 2026-05-21 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_score', models.IntegerField(default=0)),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('total_orders', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
